rabbit@Ahasver:~/.cpanm/work/1465578850.23395/DBIx-Error-1.0.1$ prove -I/home/rabbit/devel/dbic/lib -l t/20-dbic.t 
t/20-dbic.t .. 1/? 


I got called with DBIx::Error::UniqueViolation=HASH(0x36bf9e0)
   at /home/rabbit/.cpanm/work/1465578850.23395/DBIx-Error-1.0.1/lib/DBIx/Error.pm line 309.
	DBIx::Error::__ANON__() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1087
	eval {...} called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1108
	DBIx::Class::Schema::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 112
	DBIx::Class::Storage::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 177
	DBIx::Class::Storage::BlockRunner::__ANON__() called at /home/rabbit/perl5/perlbrew/perls/5.16.2/lib/site_perl/5.16.2/Context/Preserve.pm line 27
	Context::Preserve::preserve_context() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 206
	DBIx::Class::Storage::BlockRunner::_run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 105
	DBIx::Class::Storage::BlockRunner::run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 186
	DBIx::Class::Storage::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/DBI.pm line 867
	DBIx::Class::Storage::DBI::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 654
	DBIx::Class::Schema::txn_do() called at t/20-dbic.t line 38
	Test::Exception::throws_ok() called at t/20-dbic.t line 39



I got called with DBIx::Error::NotNullViolation=HASH(0x36157a0)
   at /home/rabbit/.cpanm/work/1465578850.23395/DBIx-Error-1.0.1/lib/DBIx/Error.pm line 309.
	DBIx::Error::__ANON__() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1087
	eval {...} called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1108
	DBIx::Class::Schema::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 112
	DBIx::Class::Storage::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 177
	DBIx::Class::Storage::BlockRunner::__ANON__() called at /home/rabbit/perl5/perlbrew/perls/5.16.2/lib/site_perl/5.16.2/Context/Preserve.pm line 27
	Context::Preserve::preserve_context() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 206
	DBIx::Class::Storage::BlockRunner::_run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 105
	DBIx::Class::Storage::BlockRunner::run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 186
	DBIx::Class::Storage::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/DBI.pm line 867
	DBIx::Class::Storage::DBI::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 654
	DBIx::Class::Schema::txn_do() called at t/20-dbic.t line 47
	Test::Exception::throws_ok() called at t/20-dbic.t line 48



I got called with execute_for_fetch() aborted with 'PRIMARY KEY must be unique' at populate slice:
{
  id => 1,
  name => "You"
}

   at /home/rabbit/.cpanm/work/1465578850.23395/DBIx-Error-1.0.1/lib/DBIx/Error.pm line 309.
	DBIx::Error::__ANON__() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1087
	eval {...} called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1108
	DBIx::Class::Schema::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 112
	DBIx::Class::Storage::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/DBI.pm line 2382
	DBIx::Class::Storage::DBI::_dbh_execute_for_fetch() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/DBI.pm line 2270
	DBIx::Class::Storage::DBI::_insert_bulk() called at /home/rabbit/devel/dbic/lib/DBIx/Class/ResultSet.pm line 2435
	DBIx::Class::ResultSet::populate() called at t/20-dbic.t line 57
	main::__ANON__() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 130
	DBIx::Class::Storage::BlockRunner::try {...} () called at /home/rabbit/perl5/perlbrew/perls/5.16.2/lib/site_perl/5.16.2/Try/Tiny.pm line 92
	eval {...} called at /home/rabbit/perl5/perlbrew/perls/5.16.2/lib/site_perl/5.16.2/Try/Tiny.pm line 83
	Try::Tiny::try() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 134
	DBIx::Class::Storage::BlockRunner::__ANON__() called at /home/rabbit/perl5/perlbrew/perls/5.16.2/lib/site_perl/5.16.2/Context/Preserve.pm line 22
	Context::Preserve::preserve_context() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 206
	DBIx::Class::Storage::BlockRunner::_run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 105
	DBIx::Class::Storage::BlockRunner::run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 186
	DBIx::Class::Storage::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/DBI.pm line 867
	DBIx::Class::Storage::DBI::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 654
	DBIx::Class::Schema::txn_do() called at t/20-dbic.t line 60
	Test::Exception::throws_ok() called at t/20-dbic.t line 61



I got called with DBIx::Error::GeneralError=HASH(0x36aca60)
   at /home/rabbit/.cpanm/work/1465578850.23395/DBIx-Error-1.0.1/lib/DBIx/Error.pm line 309.
	DBIx::Error::__ANON__() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1087
	eval {...} called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1108
	DBIx::Class::Schema::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 112
	DBIx::Class::Storage::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 177
	DBIx::Class::Storage::BlockRunner::__ANON__() called at /home/rabbit/perl5/perlbrew/perls/5.16.2/lib/site_perl/5.16.2/Context/Preserve.pm line 27
	Context::Preserve::preserve_context() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 206
	DBIx::Class::Storage::BlockRunner::_run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 105
	DBIx::Class::Storage::BlockRunner::run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 186
	DBIx::Class::Storage::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/DBI.pm line 867
	DBIx::Class::Storage::DBI::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 654
	DBIx::Class::Schema::txn_do() called at t/20-dbic.t line 60
	Test::Exception::throws_ok() called at t/20-dbic.t line 61



I got called with TestError=HASH(0x37847d8)
   at /home/rabbit/.cpanm/work/1465578850.23395/DBIx-Error-1.0.1/lib/DBIx/Error.pm line 309.
	DBIx::Error::__ANON__() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1087
	eval {...} called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 1108
	DBIx::Class::Schema::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 112
	DBIx::Class::Storage::throw_exception() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 177
	DBIx::Class::Storage::BlockRunner::__ANON__() called at /home/rabbit/perl5/perlbrew/perls/5.16.2/lib/site_perl/5.16.2/Context/Preserve.pm line 27
	Context::Preserve::preserve_context() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 206
	DBIx::Class::Storage::BlockRunner::_run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/BlockRunner.pm line 105
	DBIx::Class::Storage::BlockRunner::run() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage.pm line 186
	DBIx::Class::Storage::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Storage/DBI.pm line 867
	DBIx::Class::Storage::DBI::txn_do() called at /home/rabbit/devel/dbic/lib/DBIx/Class/Schema.pm line 654
	DBIx::Class::Schema::txn_do() called at t/20-dbic.t line 69
	Test::Exception::throws_ok() called at t/20-dbic.t line 70
t/20-dbic.t .. ok   
All tests successful.
Files=1, Tests=6,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.56 cusr  0.04 csys =  0.62 CPU)
Result: PASS
