<!DOCTYPE html>

<html lang="en">
  <head>
    <title>Bug #43759 for Exception-Class-TryCatch: Questions about TryCatch&#39;s philosophy</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- The X-UA-Compatible <meta> tag above must be very early in <head> -->

    <script>
if (window.top !== window.self) {
    document.write = "";

    window.top.location = window.self.location;

    setTimeout(function(){
        document.body.innerHTML = "";
    }, 1);

    window.self.onload = function(){
        document.body.innerHTML = "";
    };
}
</script>



<link rel="shortcut icon" href="/NoAuth/images/favicon.png" type="image/png" />
<link rel="stylesheet" href="/NoAuth/css/aileron-squished-00f758259152f8b6670ee485f462e6b8.css" type="text/css" media="all" />
<link rel="stylesheet" href="/NoAuth/css/print.css" type="text/css" media="print" />




<script type="text/javascript" src="/NoAuth/js/squished-42167f2409ce368da2d31038e5cb2a57.js"></script>

<script type="text/javascript"><!--
	jQuery( loadTitleBoxStates );

--></script>


<!--[if lt IE 8]>
<link rel="stylesheet" href="/NoAuth/css/aileron/msie.css" type="text/css" media="all" />
<![endif]-->
<!--[if lt IE 7]>
<link rel="stylesheet" href="/NoAuth/css/aileron/msie6.css" type="text/css" media="all" />
<![endif]-->
<script type="text/javascript">
jQuery(document).ready(function(){
    jQuery.fn.supersubs.defaults = {
        maxWidth: 30,
        extraWidth: 2
    };

    jQuery("#app-nav.toplevel").addClass('sf-menu sf-js-enabled sf-shadow').supersubs().superfish({ speed: 'fast' });
    jQuery("#page-menu.toplevel").addClass('sf-menu sf-js-enabled').supersubs().superfish({ dropShadows: false, speed: 'fast' }).supposition();
});
</script>


<!-- Site CSS from theme editor -->
<style type="text/css" media="all" id="sitecss">
</style>

<meta name="google-site-verification" content="kD3-uEJK1AkTqaC-rckcSt_HPkAj674DPPuEN6i-y0g" />

</head>
  <body class="aileron sidebyside" id="comp-Public-Bug-Display">

<div id="logo">
<a href="/"><img
    src="/NoAuth/images/cpan.png"
    alt="CPAN"
    width="181"
    height="38" /></a>
    <span class="rtname">RT for rt.cpan.org</span>
</div>


<div id="quickbar">
  <div id="quick-personal">
    <span class="hide"><a href="#skipnav">Skip Menu</a> | </span>
</div>

</div>
<div id="header"><h1>Bug #43759 for Exception-Class-TryCatch: Questions about TryCatch&#39;s philosophy</h1></div>



<div id="page-navigation"><ul id="page-menu" class="toplevel">
 <li id="li-page-active_bugs"><a id="page-active_bugs" class="menu-item " href="/Public/Dist/Exception-Class-TryCatch/Active/">Active bugs</a></li>
 <li id="li-page-resolved_bugs"><a id="page-resolved_bugs" class="menu-item " href="/Public/Dist/Exception-Class-TryCatch/Resolved/">Resolved bugs</a></li>
 <li id="li-page-rejected_bugs"><a id="page-rejected_bugs" class="menu-item " href="/Public/Dist/Exception-Class-TryCatch/Rejected/">Rejected bugs</a></li>
 <li id="li-page-report"><a id="page-report" class="menu-item " href="/Public/Dist/Exception-Class-TryCatch/Active/"></a></li>
</ul></div>
<div id="topactions">



</div>
<div id="body">


<a name="skipnav" id="skipnav" accesskey="8"></a>




<div id="external_bugtracker">
<h3>Preferred bug tracker</h3>
<p>
<div>Please visit the <a href="https://github.com/dagolden/Exception-Class-TryCatch/issues">preferred bug tracker</a> to report your issue.</div>
</p>
</div>

<p>This queue is for tickets about the <a href="https://metacpan.org/release/Exception-Class-TryCatch">Exception-Class-TryCatch CPAN distribution</a>.</p>





<div class="">
  <div class="titlebox" id="">
  <div class="titlebox-title">
    <span class="widget"><a href="#" onclick="return rollup('TitleBox\x2D\x2D\x5FPublic\x5FBug\x5FDisplay\x5Fhtml\x2D\x2D\x2D\x2D\x2D\x2DUmVwb3J0IGluZm9ybWF0aW9u\x2D\x2D\x2D0');" title="Toggle visibility"></a></span>
    <span class="left">Report information</span>
    <span class="right-empty">		    </span>
  </div>
  <div class="titlebox-content " id="TitleBox--_Public_Bug_Display_html------UmVwb3J0IGluZm9ybWF0aW9u---0">


<table width="100%" class="ticket-summary">
<tr>
  <td valign="top" class="boxcontainer">
    <div class="ticket-info-basics">
  <div class="titlebox ticket-info-basics " id="">
  <div class="titlebox-title">
    <span class="widget"><a href="#" onclick="return rollup('TitleBox\x2D\x2D\x5FPublic\x5FBug\x5FDisplay\x5Fhtml\x2D\x2Dticket\x2Dinfo\x2Dbasics\x2D\x2D\x2D\x2DVGhlIEJhc2ljcw\x5F\x5F\x2D\x2D\x2D0');" title="Toggle visibility"></a></span>
    <span class="left">The Basics</span>
    <span class="right-empty">		    </span>
  </div>
  <div class="titlebox-content " id="TitleBox--_Public_Bug_Display_html--ticket-info-basics----VGhlIEJhc2ljcw__---0">


        <table>
  <tr class="id">
    <td class="label">Id:</td>
    <td class="value">43759</td>
  </tr>
  <tr class="status">
    <td class="label">Status:</td>
    <td class="value">resolved</td>
  </tr>
  <tr class="priority">
    <td class="label">Priority:</td>
    <td class="value">0/
</td>
  </tr>
  <tr class="queue">
    <td class="label">Queue:</td>
    <td class="value"><a href="/Public/Dist/Exception-Class-TryCatch/Active/">Exception-Class-TryCatch</a>
</td>
  </tr>
</table>

        <hr class="clear" />
  </div>
</div>




</div>


    <div class="ticket-info-people">
  <div class="titlebox ticket-info-people " id="">
  <div class="titlebox-title">
    <span class="widget"><a href="#" onclick="return rollup('TitleBox\x2D\x2D\x5FPublic\x5FBug\x5FDisplay\x5Fhtml\x2D\x2Dticket\x2Dinfo\x2Dpeople\x2D\x2D\x2D\x2DUGVvcGxl\x2D\x2D\x2D0');" title="Toggle visibility"></a></span>
    <span class="left">People</span>
    <span class="right-empty">		    </span>
  </div>
  <div class="titlebox-content " id="TitleBox--_Public_Bug_Display_html--ticket-info-people----UGVvcGxl---0">


        <table>
  <tr>
    <td class="label">Owner:</td>
    <td class="value">Nobody in particular
    
    </td>
  </tr>
  <tr>
    <td class="labeltop">Requestors:</td>
    <td class="value">
QKoch [...] web.de

<br />

</td>
  </tr>
  <tr>
    <td class="labeltop">Cc:</td>
    <td class="value">

</td>
  </tr>
  <tr>
    <td class="labeltop">AdminCc:</td>
    <td class="value">

</td>
  </tr>
</table>

        <hr class="clear" />
  </div>
</div>




</div>



  </td>
  <td valign="top" class="boxcontainer">
    
    <div class="ticket-info-cfs">
  <div class="titlebox ticket-info-cfs " id="">
  <div class="titlebox-title">
    <span class="widget"><a href="#" onclick="return rollup('TitleBox\x2D\x2D\x5FPublic\x5FBug\x5FDisplay\x5Fhtml\x2D\x2Dticket\x2Dinfo\x2Dcfs\x2D\x2D\x2D\x2DQnVnIEluZm9ybWF0aW9u\x2D\x2D\x2D0');" title="Toggle visibility"></a></span>
    <span class="left">Bug Information</span>
    <span class="right-empty">		    </span>
  </div>
  <div class="titlebox-content " id="TitleBox--_Public_Bug_Display_html--ticket-info-cfs----QnVnIEluZm9ybWF0aW9u---0">

 
        <table>
  <tr id="CF-1-ShowRow">
    <td class="label">Severity:</td>
    <td class="value">
<i>(no value)</i>
    </td>
  </tr>
  <tr id="CF-12376-ShowRow">
    <td class="label">Broken in:</td>
    <td class="value">
<i>(no value)</i>
    </td>
  </tr>
  <tr id="CF-12377-ShowRow">
    <td class="label">Fixed in:</td>
    <td class="value">
<i>(no value)</i>
    </td>
  </tr>
</table>


        <hr class="clear" />
  </div>
</div>




</div>


    <div class="ticket-info-attachments">
  <div class="titlebox ticket-info-attachments " id="">
  <div class="titlebox-title inverse">
    <span class="widget"><a href="#" onclick="return rollup('TitleBox\x2D\x2D\x5FPublic\x5FBug\x5FDisplay\x5Fhtml\x2D\x2Dticket\x2Dinfo\x2Dattachments\x2D\x2D\x2D\x2DQXR0YWNobWVudHM\x5F\x2D\x2D\x2D0');" title="Toggle visibility"></a></span>
    <span class="left">Attachments</span>
    <span class="right-empty">		    </span>
  </div>
  <div class="titlebox-content " id="TitleBox--_Public_Bug_Display_html--ticket-info-attachments----QXR0YWNobWVudHM_---0">




smime.p7s<br />
<ul>


<li><font size="-2">
<a href="/Ticket/Attachment/571715/288392/smime.p7s">
Sun Mar 01 20:25:07 2009 (5.4k) by QKoch [...] web.de
</a>
</font></li>
</ul>


TestExceptionClass.pl<br />
<ul>


<li><font size="-2">
<a href="/Ticket/Attachment/571715/288391/TestExceptionClass.pl">
Sun Mar 01 20:25:07 2009 (5.9k) by QKoch [...] web.de
</a>
</font></li>
</ul>

    <hr class="clear" />
  </div>
</div>




</div>







  </td>
</tr>
</table>

    <hr class="clear" />
  </div>
</div>




</div>


<br />


<div class="history">
<div class="titlebox" id="">
  <div class="titlebox-title">
    <span class="widget"><a href="#" onclick="return rollup('TitleBox\x2D\x2D\x5FPublic\x5FBug\x5FDisplay\x5Fhtml\x2D\x2D\x2D\x2D\x2D\x2DSGlzdG9yeQ\x5F\x5F\x2D\x2D\x2D0');" title="Toggle visibility"></a></span>
    <span class="left">History</span>
    <span class="right">		<a href="#" data-direction="open" onclick="return toggle_all_folds(this, 'Show\x20all\x20quoted\x20text', 'Hide\x20all\x20quoted\x20text');">Show all quoted text</a>    </span>
  </div>
  <div class="titlebox-content " id="TitleBox--_Public_Bug_Display_html------SGlzdG9yeQ__---0">


<div id="ticket-history">
<div class="ticket-transaction message Create odd">
<div class="ticket-transaction">
  <div class="metadata">
    <span class="type">
      &nbsp;      
    </span>
    <span class="date">Sun&nbsp;Mar&nbsp;01&nbsp;20:25:07&nbsp;2009</span>
    <span class="description">QKoch [...] web.de -  Ticket created</span>
    <span class="time-taken"></span>    <span class="actions hidden"></span>
  </div>
    <div class="content">
      
<table>
  <tr>
    <td align="right" class="message-header-key">Subject:</td>
    <td class="message-header-value"> Questions about TryCatch&#39;s philosophy</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">Date:</td>
    <td class="message-header-value"> Sun, 01 Mar 2009 19:36:44 +0100</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">To:</td>
    <td class="message-header-value"> bug-Exception-Class-TryCatch [...] rt.cpan.org</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">From:</td>
    <td class="message-header-value"> Oliver Koch &lt;QKoch [...] web.de&gt;</td>
  </tr>
</table>
<div class="messageattachments">
<div class="downloadattachment">
<a href="/Ticket/Attachment/571715/288392/smime.p7s">Download smime.p7s</a><br />
<span class="downloadcontenttype">application/x-pkcs7-signature 5.4k</span>
</div>
<div class="messagebody">
<p>Message body not shown because it is not plain text.</p></div>
</div>
<div class="messageattachments">

<div class="messagebody">
<div class="message-stanza plain-text-white-space">use 5.8.8;
use strict;
use Data::Dumper 2.121;
use Exception::Class  1.26 &#40;
  &#39;Ex::TestExceptionClass&#39;,
  &#39;Ex::TestExceptionClass::Test1&#39;      =&gt; { isa =&gt; &#39;Ex::TestExceptionClass&#39; },
  &#39;Ex::TestExceptionClass::Test2&#39;      =&gt; { isa =&gt; &#39;Ex::TestExceptionClass&#39; },
  &#39;Ex::TestExceptionClass::Test2Sub&#39;   =&gt; { isa =&gt; &#39;Ex::TestExceptionClass&#39; },
  &#39;Ex::TestExceptionClass::Test3&#39;      =&gt; { isa =&gt; &#39;Ex::TestExceptionClass&#39; },
  &#39;Ex::TestExceptionClass::Test3::Ex1&#39; =&gt; { isa =&gt; &#39;Ex::TestExceptionClass::Test3&#39; },
  &#39;Ex::TestExceptionClass::Test3::Ex2&#39; =&gt; { isa =&gt; &#39;Ex::TestExceptionClass::Test3&#39; },
  &#39;Ex::TestExceptionClass::Test3::Ex3&#39; =&gt; { isa =&gt; &#39;Ex::TestExceptionClass::Test3&#39; }
&#41;;
use Exception::Class::TryCatch 1.12; 

# Declare prototypes.
sub Test1&#40;&#41;;
sub Test2Sub&#40;&#41;;
sub Test2&#40;&#41;;
sub Test3&#40;&#41;;
sub ExitProgram&#40;$&#41;;

print &#34;$0 started.\n&#34;;

select STDERR; $| = 1;  # make unbuffered
select STDOUT; $| = 1;  # make unbuffered

# Initialize global variables.
my $TestNr = 0;

# ****************
$TestNr++;
print&#40;&#34;$TestNr.&#41; Simple try/throw/catch.\n&#34;&#41;; 
print &#34;\$@ = $@\n&#34;;  
try eval {
  throw Ex::TestExceptionClass 
    &#39;Ex::TestExceptionClass thrown!&#39;;
}; 
print &#34;\$@ = $@\n&#34;;  
if&#40;catch my $Ex&#41; {
  print&#40;&#34;Caught &#34;, ref&#40;$Ex&#41;, &#34;\n&#34;&#41;;
  print&#40;$Ex-&gt;message, &#34;\n&#34;&#41;;
}
print &#34;\$@ = $@\n&#34;;  
if&#40;catch my $Ex&#41; {
  print&#40;&#34;Caught &#34;, ref&#40;$Ex&#41;, &#34;\n&#34;&#41;;
  print&#40;&#34;I would expect, that no exception was caught!\n&#34;&#41;;
  print&#40;&#34;Is exception still on stack?\n&#34;&#41;;
  $@ = &#34;&#34;;
} else {
  print&#40;&#34;No exception on stack.\n&#34;&#41;;  
}
print &#34;\$@ = $@\n&#34;;  
if&#40;catch my $Ex&#41; {
  print&#40;&#34;Caught &#34;, ref&#40;$Ex&#41;, &#34;\n&#34;&#41;;
  print&#40;&#34;Is exception still on stack?\n&#34;&#41;;
} else {
  print&#40;&#34;No, but \$@ must be reset, too.\n&#34;&#41;;  
}

# ****************
$TestNr++;
print&#40;&#34;\n&#34;&#41;;
print&#40;&#34;$TestNr.&#41; Simple try/catch without throw.\n&#34;&#41;; 
print &#34;\$@ = $@\n&#34;;  
try eval {
  die&#40;&#34;Just a simple die.&#34;&#41;;
}; 
print &#34;\$@ = $@\n&#34;;  
if&#40;catch my $Ex&#41; {
  print&#40;&#34;Caught &#34;, ref&#40;$Ex&#41;, &#34;\n&#34;&#41;;
  print&#40;$Ex-&gt;message, &#34;\n&#34;&#41;;
  if&#40;$Ex-&gt;isa&#40;&#39;Exception::Class::Base&#39;&#41;&#41; {
    print&#40;&#34;Why is a die&#40;&#41; of class &#39;Exception::Class::Base&#39;?\n&#34;&#41;;
    print&#40;&#34;I would expect something like &#39;Exception::Die&#39;!\n&#34;&#41;;
  } else {
    print&#40;&#34;Something unexpected happened &#40;maybe a die&#41;.\n&#34;&#41;;    
  }  
}
print &#34;\$@ = $@\n&#34;;  
if&#40;catch my $Ex&#41; {
  print&#40;&#34;Caught &#34;, ref&#40;$Ex&#41;, &#34;\n&#34;&#41;;
  print&#40;&#34;I would expect, that no exception was caught!\n&#34;&#41;;
  print&#40;&#34;Is exception still on stack?\n&#34;&#41;;
  $@ = &#34;&#34;;
} else {
  print&#40;&#34;No exception on stack.\n&#34;&#41;;  
}
print &#34;\$@ = $@\n&#34;;  
if&#40;catch my $Ex&#41; {
  print&#40;&#34;Caught &#34;, ref&#40;$Ex&#41;, &#34;\n&#34;&#41;;
  print&#40;&#34;Is exception still on stack?\n&#34;&#41;;
} else {
  print&#40;&#34;No, but \$@ must be reset, too.\n&#34;&#41;;  
}

# ****************
$TestNr++;
print&#40;&#34;\n&#34;&#41;;
print&#40;&#34;$TestNr.&#41; throw in a subroutine caught outside.\n&#34;&#41;;
print &#34;\$@ = $@\n&#34;;  
Test1&#40;&#41;;
print &#34;\$@ = $@\n&#34;;  
if&#40;catch my $Ex&#41; {
  print&#40;&#34;Caught &#34;, ref&#40;$Ex&#41;, &#34;\n&#34;&#41;;
  if&#40;$Ex-&gt;isa&#40;&#39;Ex::TestExceptionClass::Test1&#39;&#41;&#41; {
    print&#40;$Ex-&gt;message, &#34;\n&#34;&#41;;
  } else {
    print&#40;&#34;Unexpected exception!\n&#34;&#41;;
  }
}
$@ = &#34;&#34;;

# ****************
$TestNr++;
print&#40;&#34;\n&#34;&#41;;
print&#40;&#34;$TestNr.&#41; throw and rethrow in subroutines caught outside, if not caught inside.\n&#34;&#41;;
print &#34;\$@ = $@\n&#34;;  
try eval { 
  Test2&#40;&#41;; 
};
print &#34;\$@ = $@\n&#34;;  
if&#40;catch my $Ex&#41; {
  print&#40;&#34;Caught &#34;, ref&#40;$Ex&#41;, &#34;\n&#34;&#41;;
  if&#40;$Ex-&gt;isa&#40;&#39;Ex::TestExceptionClass::Test2&#39;&#41;&#41; {
    print&#40;$Ex-&gt;message, &#34;\n&#34;&#41;;
  } else {
    print&#40;&#34;Unknown exception!\n&#34;&#41;;
    print&#40;$Ex-&gt;message, &#34;\n&#34;&#41;;
  }
} else {
  print&#40;&#34;No further exceptions.\n&#34;&#41;; 
}
$@ = &#34;&#34;;

# ****************
$TestNr++;
print&#40;&#34;\n&#34;&#41;;
print&#40;&#34;$TestNr.&#41; 3 throws and a die in a subroutine, stack cleaned up outside.\n&#34;&#41;;
print &#34;\$@ = $@\n&#34;;  
Test3&#40;&#41;;
print &#34;\$@ = $@\n&#34;;  
if&#40;catch my $Ex&#41; {             # I miss a simple boolean function indicating,  
  try eval { $Ex-&gt;rethrow&#40;&#41; }; # that&#39;s something on the exception stack!
  $@ = &#34;&#34;; # Required to avoid endless loop.
  while &#40;catch my $Ex&#41;{
    print&#40;&#34;Caught &#34;, ref&#40;$Ex&#41;, &#34;\n&#34;&#41;;
    if&#40;$Ex-&gt;isa&#40;&#39;Ex::TestExceptionClass::Test3&#39;&#41;&#41; {
      print&#40;$Ex-&gt;message, &#34;\n&#34;&#41;;
    } else {
      print&#40;&#34;Unexpected exception!\n&#34;&#41;;
      print&#40;$Ex-&gt;message, &#34;\n&#34;&#41;;
    }
  }  
  ExitProgram&#40;-4&#41;;
}

ExitProgram&#40;0&#41;;

sub Test1 &#40;&#41; {
  print &#34;Test1: \$@ = $@\n&#34;;  
  try eval {
    throw Ex::TestExceptionClass::Test1
      &#39;Ex::TestExceptionClass::Test1 thrown!&#39;;
  }; 
  print &#34;Test1: \$@ = $@\n&#34;;  
}

sub Test2Sub &#40;&#41; {
  print &#34;Test2Sub: \$@ = $@\n&#34;;  
  #try eval {
    throw Ex::TestExceptionClass::Test2Sub
      &#39;Ex::TestExceptionClass::Test2Sub thrown!&#39;;
  #}; 
  print &#34;Test2Sub: \$@ = $@\n&#34;;  
}

sub Test2 &#40;&#41; {
  print &#34;Test2: \$@ = $@\n&#34;;  
  try eval {
    Test2Sub&#40;&#41;;
    print &#34;Test2: \$@ = $@\n&#34;;  
    throw Ex::TestExceptionClass::Test2
      &#39;Ex::TestExceptionClass::Test2 thrown!&#39;;
  }; 
  print &#34;Test2: \$@ = $@\n&#34;;  
  if&#40;catch my $Ex&#41; {
    print&#40;&#34;Caught &#34;, ref&#40;$Ex&#41;, &#34;\n&#34;&#41;;
    if&#40;$Ex-&gt;isa&#40;&#39;Ex::TestExceptionClass::Test2&#39;&#41;&#41; {
      print&#40;$Ex-&gt;message, &#34;\n&#34;&#41;;
    } else {
      print&#40;&#34;Unexpected exception!\n&#34;&#41;;
      print&#40;$Ex-&gt;message, &#34;\n&#34;&#41;;
      $Ex-&gt;rethrow&#40;&#41;;
    }    
  }
  print &#34;Test2: \$@ = $@\n&#34;;   
}

sub Test3 &#40;&#41; {
  print &#34;Test3: \$@ = $@\n&#34;;  
  try eval {
    throw Ex::TestExceptionClass::Test3::Ex1 
      &#39;Ex::TestExceptionClass::Test3::Ex1 thrown!&#39;;
  }; 
  print &#34;Test3: \$@ = $@\n&#34;;  
  try eval {
    throw Ex::TestExceptionClass::Test3::Ex2
      &#39;Ex::TestExceptionClass::Test3::Ex2 thrown!&#39;;
  }; 
  print &#34;Test3: \$@ = $@\n&#34;;  
  try eval {
    die &#34;Died for some reason!&#34;;
  }; 
  print &#34;Test3: \$@ = $@\n&#34;;  
  try eval {
    throw Ex::TestExceptionClass::Test3::Ex3
      &#39;Ex::TestExceptionClass::Test3::Ex3 thrown!&#39;;
  }; 
  print &#34;Test3: \$@ = $@\n&#34;;  
}

sub ExitProgram &#40;$&#41; {
  my $ExitCode = shift;
  
  if&#40;$ExitCode == 0&#41; {
    print &#34;$0 finished successfully.&#34;;
  } else {    
    print &#34;$0 finished with exit code $ExitCode.&#34;;
  }   
  exit&#40;$ExitCode&#41;;
}

__END__;</div></div>
</div>
<div class="messageattachments">

<div class="messagebody">
<div class="message-stanza plain-text-white-space">Dear David,

At first: Many thanks for your excellent extension to Exception::Class.
However, I have a few questions about TryCatch&#39;s philosophy.
I added a perl script to demonstrate, how I intend to use TryCatch 
module. But some of my ideas doesn&#39;t seem to be fully compatible with 
TryCatch&#39;s philosophy.

Example 1:
According documentation: &#34;The exception is either popped from a hidden 
error stack &#40;see try&#41; or, if the stack is empty, taken from the current 
value of $@.&#34;
My confusion starts after catch&#40;&#41; caught &#40;and popped&#41; the thrown 
exception from the error stack. The copy of this exception is still in 
$@ and the next catch&#40;&#41; catches the same &#39;exception&#39; again. The next 
point is, that $@ isn&#39;t &#34;popped&#34; from this &#34;error stack&#34;.
*From this example I would expect, that the content of $@ is ignored by 
catch&#40;&#41;, because it&#39;s just a copy of the exception on the error stack.
*
Example 2:
This example is the same as the example above, but a simple die is used 
instead of a throw&#40;&#41;. Again $@ isn&#39;t &#34;cleaned&#34; by catch&#40;&#41;, so I have to 
do this manually, to avoid a repeated catch of the same message. But 
it&#39;s difficult to decide, whether $@ must be reset or not, because I 
can&#39;t notice whether it caught an exception or a $@ entry. Even from the 
exception class &#40;Exception::Class::Base&#41; it can&#39;t be concluded for sure, 
what was the source of the caught exception.
*I suggest to change the class of &#34;$@ exceptions&#34; to something unique 
like &#34;Exception::Unexpected::Die&#34; &#40;if &#34;thrown&#34; by a die&#41;.*

*As a consequence from example 1 and 2 I feel, that the approach to use 
the error stack AND $@ for catch&#40;&#41;, leads easily to confusing 
situations. I think, it would be clearer, that catch&#40;&#41; ignores $@ and 
try&#40;&#41; pushes $@ entries to the error stack as every other exceptions 
with a special exception class.
*
Example 3:
This example shows, that I possibly throw an exception in a subroutine, 
that is processed outside the subroutine.
Works fine!

Example 4:
This example shows how an &#34;unexpected&#34; exception is passed upwardly, if 
it couldn&#39;t be handled inside the subroutine.
Works fine!

Note:
If you uncomment the try eval {} in Test2Sub&#40;&#41;, I expected to catch the 
first exception from Test2Sub&#40;&#41; in the main part. But it seems to be gone.
*Where is it?*

Example 5:
In this example a couple of exceptions are thrown in a subroutine, that 
should be handled outside all at once. &#40;One possible idea is to clean up 
the error stack at program end and exit with an error code.&#41;
*Here I miss something to avoid the &#34;if&#40;catch&#41; - try eval { rethrow } - 
while&#40;catch&#41;&#34; construct. I suggest - according to &#34;scalar&#40;@error_stack&#41;&#34; 
- a function like &#34;ExceptionsOnStack&#40;&#41;&#34;. This would allow a simpler 
approach like &#34;while&#40;ExceptionsOnStack&#40;&#41;&#41; { ... }&#34;.*


To conclude, I want to confirm again, that TryCatch module is very 
useful for me and - please - my remarks shouldn&#39;t be taken as a critique!
Maybe, I have the wrong view on how the module should be used. So, I 
would be really thankful for clarification.

Many thanks in advance and
kind regards,

Oliver
</div></div>

<div class="messagebody">
</div>
</div>
    </div>
</div>
</div>
<div class="ticket-transaction message Correspond even">
<div class="ticket-transaction">
  <div class="metadata">
    <span class="type">
      &nbsp;      
    </span>
    <span class="date">Sun&nbsp;Mar&nbsp;01&nbsp;22:01:23&nbsp;2009</span>
    <span class="description">dagolden [...] cpan.org -  Correspondence added</span>
    <span class="time-taken"></span>    <span class="actions hidden"></span>
  </div>
    <div class="content">
      

<div class="messagebody">
<div class="message-stanza plain-text-white-space">It&#39;s a little hard to follow exactly what you&#39;re trying to achieve.  So
I&#39;ve quickly skimmed your code and will give you my snap reaction.  Let
me know if that helps.  If not, maybe you could elaborate with more
specifics on how you&#39;re trying to handle errors and I&#39;ll see if I can
help figure out if TryCatch is right for you.

I think that the main issue is that you&#39;re mixing usage of try/catch and
$@.  The philosophy of TryCatch is that once you start using it, you
need to forget about $@ entirely.

Think about how a normal &#34;eval {}&#34; works.  At the end of the eval, $@ is
guaranteed to be either an exception or the empty string.  &#40;Side note --
the exception could be from an eval {} in the DESTROY from an object
that went out of scope at the end of the original eval; this is viewed
by many to be either a perl bug or a class design bug having eval in
DESTROY.&#41;

So &#34;try eval {}&#34; is just &#34;try&#40; eval {} &#41;&#34; so immediately after eval {},
the result is passed to try.  At that precise moment, when $@ is either
an exception or the empty string, the value in $@ is pushed onto a stack.  

Then later, when you want to know the result of that *specific* eval,
you call catch&#40;&#41; to pop the value off the stack.  In between try&#40;&#41; and
catch&#40;&#41;, anything could happen and thus $@ may or may not be related to
the original eval.

One other thing that occurs to me is that I think I assume that
try/catch will happen in the same scope.  That&#39;s not strictly necessary,
but since you need to pair one &#40;and only one&#41; catch with each try, I&#39;d
worry trying to guarantee that if you&#39;re calling try&#40;&#41; in a sub and
catching it the calling sub.

In one of the examples, you&#39;re calling try&#40;&#41;, try&#40;&#41;, try&#40;&#41; before doing
any catching.  That&#39;s something you&#39;re explicitly warned not to do.  See
the documentation about try&#40;&#41; that starts &#34;try must always be properly
bracketed with a matching catch&#34;.

Another side note -- die becomes an Exception::Class::Base because I
don&#39;t want to try to define an exception hierarchy.  What if something
else defined Exception::Die?  The only thing I know is safe is
Exception::Class::Base.

Does any of that clarify? 

-- David
</div></div>
    </div>
</div>
</div>
<div class="ticket-transaction basics Status odd">
<div class="ticket-transaction">
  <div class="metadata">
    <span class="type">
      &nbsp;      
    </span>
    <span class="date">Sun&nbsp;Mar&nbsp;01&nbsp;22:01:24&nbsp;2009</span>
    <span class="description">The RT System itself -  Status changed from &#39;new&#39; to &#39;open&#39;</span>
    <span class="time-taken"></span>    <span class="actions hidden"></span>
  </div>
    <div class="content">
    </div>
</div>
</div>
<div class="ticket-transaction message Correspond even">
<div class="ticket-transaction">
  <div class="metadata">
    <span class="type">
      &nbsp;      
    </span>
    <span class="date">Mon&nbsp;Mar&nbsp;02&nbsp;17:39:14&nbsp;2009</span>
    <span class="description">QKoch [...] web.de -  Correspondence added</span>
    <span class="time-taken"></span>    <span class="actions hidden"></span>
  </div>
    <div class="content">
      
<table>
  <tr>
    <td align="right" class="message-header-key">Subject:</td>
    <td class="message-header-value"> Re: [rt.cpan.org #43759] Questions about TryCatch&#39;s philosophy</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">Date:</td>
    <td class="message-header-value"> Mon, 02 Mar 2009 23:14:11 +0100</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">To:</td>
    <td class="message-header-value"> bug-Exception-Class-TryCatch [...] rt.cpan.org</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">From:</td>
    <td class="message-header-value"> Oliver Koch &lt;QKoch [...] web.de&gt;</td>
  </tr>
</table>

<div class="messagebody">
<div class="message-stanza plain-text-white-space">Dear David,

many thanks for your prompt and substantial answer.

David Golden via RT schrieb:
<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; &lt;URL: <span class="clickylink"><a target="new" rel="nofollow" href="https://rt.cpan.org/Ticket/Display.html?id=43759">https://rt.cpan.org/Ticket/Display.html?id=43759</a></span> &gt;
&gt;
&gt; It&#39;s a little hard to follow exactly what you&#39;re trying to achieve.  So
&gt; I&#39;ve quickly skimmed your code and will give you my snap reaction.  Let
&gt; me know if that helps.  If not, maybe you could elaborate with more
&gt; specifics on how you&#39;re trying to handle errors and I&#39;ll see if I can
&gt; help figure out if TryCatch is right for you.
&gt;   
</div>To clarify this a little bit and explain it in a few words:
My basic approach to exception handling is to use exceptions for error 
handling, not only for exceptional situations.
A subroutine should pass back their result value. If an error occurs, it 
should be dealt with by an exception.
<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; I think that the main issue is that you&#39;re mixing usage of try/catch and
&gt; $@.  The philosophy of TryCatch is that once you start using it, you
&gt; need to forget about $@ entirely.
&gt;
&gt; Think about how a normal &#34;eval {}&#34; works.  At the end of the eval, $@ is
&gt; guaranteed to be either an exception or the empty string.  &#40;Side note --
&gt; the exception could be from an eval {} in the DESTROY from an object
&gt; that went out of scope at the end of the original eval; this is viewed
&gt; by many to be either a perl bug or a class design bug having eval in
&gt; DESTROY.&#41;
&gt;
&gt; So &#34;try eval {}&#34; is just &#34;try&#40; eval {} &#41;&#34; so immediately after eval {},
&gt; the result is passed to try.  At that precise moment, when $@ is either
&gt; an exception or the empty string, the value in $@ is pushed onto a stack.  
&gt;
&gt; Then later, when you want to know the result of that *specific* eval,
&gt; you call catch&#40;&#41; to pop the value off the stack.  In between try&#40;&#41; and
&gt; catch&#40;&#41;, anything could happen and thus $@ may or may not be related to
&gt; the original eval.
&gt;
&gt;   
</div>The first two examples were just for me to learn how TryCatch works 
internally. So, it&#39;s clear to me, that I used too many catches for the 
number of tries according your documentation. All you&#39;ve said above is 
logically and holds perfectly as long as I combine every try&#40;&#41; with 
exactly one catch&#40;&#41;.

However, I can&#39;t really see, why catch&#40;&#41; uses $@ &#40;if the stack is 
empty&#41;. If it is guaranteed, that the content of $@ is pushed onto the 
stack and the stack is empty now, then for sure there was a catch&#40;&#41; 
before popping the exception from the stack. So every exception was 
caught &#40;= every error handled&#41;. From this point of view it makes no 
sense to catch the same &#40;old&#41; exception again &#40;and again and again&#41; from $@.

<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; One other thing that occurs to me is that I think I assume that
&gt; try/catch will happen in the same scope.  That&#39;s not strictly necessary,
&gt; but since you need to pair one &#40;and only one&#41; catch with each try, I&#39;d
&gt; worry trying to guarantee that if you&#39;re calling try&#40;&#41; in a sub and
&gt; catching it the calling sub.
&gt;   
</div> From my understanding of other exception-throwing languages like C++ or 
Java, it&#39;s usual to throw an exception, that is caught elsewhere outside 
the subroutine &#40;maybe some levels higher&#41;. And this approach makes sense 
for me in Perl, too, so I&#39;m very happy, that TryCatch implemented such 
an exception stack.
<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; In one of the examples, you&#39;re calling try&#40;&#41;, try&#40;&#41;, try&#40;&#41; before doing
&gt; any catching.  That&#39;s something you&#39;re explicitly warned not to do.  See
&gt; the documentation about try&#40;&#41; that starts &#34;try must always be properly
&gt; bracketed with a matching catch&#34;.
&gt;
&gt;   
</div>And I think, I did not so. Coming back to my first paragraph, my 
approach is, that I don&#39;t want to miss any error/exception, that was 
raised in the program. But it could be, that I don&#39;t how to handle the 
exception properly. So, I want to make sure, that at least every raised 
exception is reported to the user &#40;and every try&#40;&#41; gets its matching 
catch&#40;&#41;&#41;. This is done in the while loop after Test3&#40;&#41;.
And I assume, this is what you denoted in your documentation:

     try eval { 
         Exception::Class::Base-&gt;throw&#40;&#39;error&#39;&#41; 
     };
     do {
         # cleanup that might use &#34;try/catch&#34; again
     };
     catch my $err; # catches a matching &#34;try&#34;

I think, my Test3&#40;&#41; + while&#40;catch&#40;&#41;&#41; does more or less the same.

To conclude the above: From my point of view the exception stack is 
exactly, what I&#39;m looking for, but I think the stack should behave like 
any other stack in Perl. If I pop something from @Array and @Array is 
empty, then I get undef and not the content from e. g. $_ instead.
<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; Another side note -- die becomes an Exception::Class::Base because I
&gt; don&#39;t want to try to define an exception hierarchy.  What if something
&gt; else defined Exception::Die?  The only thing I know is safe is
&gt; Exception::Class::Base.
&gt;
&gt;   
</div>I see your point and it&#39;s a reasonable conservative approach.
On the other hand, I think, by &#34;reducing&#34; the class to 
Exception::Class::Base, information gets lost about the source of the 
exception.
Wouldn&#39;t it make sense to introduce one &#40;or maybe a few&#41; special 
sub-class&#40;es&#41; to Exception::Class::Base indicating the source of this 
non-throw&#40;&#41; exception&#40;s&#41;?
Especially, because I&#39;m not able to define this sub-class on my own for 
e. g. a die&#40;&#41;.
&#40;I&#39;m not sure, whether it&#39;s technically possible to conclude from $@ 
after an eval {}, what wrote into $@.&#41;
<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; Does any of that clarify? 
&gt;
&gt; -- David
&gt;
&gt;   
</div>
Yes and no. I&#39;m still not sure, whether I miss &#40;or misunderstood&#41; 
something.
I hope, I could make clearer, what my approach is and would be glad, if 
we could finally find a common understanding.

Regards,

Oliver
</div></div>
    </div>
</div>
</div>
<div class="ticket-transaction message Correspond odd">
<div class="ticket-transaction">
  <div class="metadata">
    <span class="type">
      &nbsp;      
    </span>
    <span class="date">Mon&nbsp;Mar&nbsp;02&nbsp;18:31:17&nbsp;2009</span>
    <span class="description">dagolden [...] cpan.org -  Correspondence added</span>
    <span class="time-taken"></span>    <span class="actions hidden"></span>
  </div>
    <div class="content">
      
<table>
  <tr>
    <td align="right" class="message-header-key">Subject:</td>
    <td class="message-header-value"> Re: [rt.cpan.org #43759] Questions about TryCatch&#39;s philosophy</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">Date:</td>
    <td class="message-header-value"> Mon, 2 Mar 2009 18:31:08 -0500</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">To:</td>
    <td class="message-header-value"> bug-Exception-Class-TryCatch [...] rt.cpan.org</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">From:</td>
    <td class="message-header-value"> David Golden &lt;dagolden [...] cpan.org&gt;</td>
  </tr>
</table>

<div class="messagebody">
<div class="message-stanza plain-text-white-space">On Mon, Mar 2, 2009 at 5:39 PM, Oliver Koch via RT &lt;bug-Exception-Class-&gt;
<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; However, I can&#39;t really see, why catch&#40;&#41; uses $@ &#40;if the stack is
&gt; empty&#41;. If it is guaranteed, that the content of $@ is pushed onto the
&gt; stack and the stack is empty now, then for sure there was a catch&#40;&#41;
&gt; before popping the exception from the stack. So every exception was
&gt; caught &#40;= every error handled&#41;. From this point of view it makes no
&gt; sense to catch the same &#40;old&#41; exception again &#40;and again and again&#41; from $@.
</div>
It&#39;s not very consistent, I admit.  It was originally intended to
support catch without needing try -- for the simplest case when
someone just wants to eval {} and have any error promoted to an
Exception::Class object.

Perhaps I can add some sort of switch that gives the stricter behavior
you&#39;re looking for.

<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed"><div class="message-stanza open">&gt;&gt; One other thing that occurs to me is that I think I assume that
&gt;&gt; try/catch will happen in the same scope.  That&#39;s not strictly necessary,
&gt;&gt; but since you need to pair one &#40;and only one&#41; catch with each try, I&#39;d
&gt;&gt; worry trying to guarantee that if you&#39;re calling try&#40;&#41; in a sub and
&gt;&gt; catching it the calling sub.
&gt;&gt;
</div>&gt;  From my understanding of other exception-throwing languages like C++ or
&gt; Java, it&#39;s usual to throw an exception, that is caught elsewhere outside
&gt; the subroutine &#40;maybe some levels higher&#41;.
</div>
I&#39;m not talking about *throwing* an exception and catching it higher.
I&#39;m talking about wrapping something in an eval and then checking for
the error higher.

It makes perfect sense to do this:

try eval { sub_that_throws_exception&#40;&#41; };
catch my $error;

It *doesn&#39;t* make sense to do this:

sub_that_might_use_try_eval&#40;&#41;;
catch my $error;

You should be catching errors where you eval.

<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; On the other hand, I think, by &#34;reducing&#34; the class to
&gt; Exception::Class::Base, information gets lost about the source of the
&gt; exception.
&gt; Wouldn&#39;t it make sense to introduce one &#40;or maybe a few&#41; special
&gt; sub-class&#40;es&#41; to Exception::Class::Base indicating the source of this
&gt; non-throw&#40;&#41; exception&#40;s&#41;?
&gt; Especially, because I&#39;m not able to define this sub-class on my own for
&gt; e. g. a die&#40;&#41;.
</div>
That&#39;s a fair point.  I suppose you could override $SIG{__DIE__} to
throw whatever exception you want, but that could break anything
*else* that uses $SIG{__DIE__}.  Perhaps I can add a way for a user to
specify an Exception::Class they want TryCatch to use for die instead
of Base.

You&#39;ve raised two good interface ideas.  I&#39;m putting them into my
&#39;todo&#39; for TryCatch.  No promises on when I&#39;ll get a chance to
implement them, though.  Feel free to ask me again in a couple weeks
if I haven&#39;t gotten around to it.

-- David
</div></div>
    </div>
</div>
</div>
<div class="ticket-transaction message Correspond even">
<div class="ticket-transaction">
  <div class="metadata">
    <span class="type">
      &nbsp;      
    </span>
    <span class="date">Tue&nbsp;Mar&nbsp;03&nbsp;15:13:11&nbsp;2009</span>
    <span class="description">QKoch [...] web.de -  Correspondence added</span>
    <span class="time-taken"></span>    <span class="actions hidden"></span>
  </div>
    <div class="content">
      
<table>
  <tr>
    <td align="right" class="message-header-key">Subject:</td>
    <td class="message-header-value"> Re: [rt.cpan.org #43759] Questions about TryCatch&#39;s philosophy</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">Date:</td>
    <td class="message-header-value"> Tue, 03 Mar 2009 21:13:28 +0100</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">To:</td>
    <td class="message-header-value"> bug-Exception-Class-TryCatch [...] rt.cpan.org</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">From:</td>
    <td class="message-header-value"> Oliver Koch &lt;QKoch [...] web.de&gt;</td>
  </tr>
</table>

<div class="messagebody">
<div class="message-stanza plain-text-white-space">

David Golden via RT schrieb:
<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; &lt;URL: <span class="clickylink"><a target="new" rel="nofollow" href="http://rt.cpan.org/Ticket/Display.html?id=43759">http://rt.cpan.org/Ticket/Display.html?id=43759</a></span> &gt;
&gt;   
&gt; It&#39;s not very consistent, I admit.  It was originally intended to
&gt; support catch without needing try -- for the simplest case when
&gt; someone just wants to eval {} and have any error promoted to an
&gt; Exception::Class object.
&gt;   
</div> From this point of view it makes perfectly sense to use $@.
<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; Perhaps I can add some sort of switch that gives the stricter behavior
&gt; you&#39;re looking for.
&gt;   
</div>Both approaches &#40;eval-catch and try eval-catch&#41; are somehow 
contradictory and a switch seems to me an appropriate solution.

<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; I&#39;m not talking about *throwing* an exception and catching it higher.
&gt; I&#39;m talking about wrapping something in an eval and then checking for
&gt; the error higher.
&gt;
&gt; It makes perfect sense to do this:
&gt;
&gt; try eval { sub_that_throws_exception&#40;&#41; };
&gt; catch my $error;
&gt;
&gt; It *doesn&#39;t* make sense to do this:
&gt;
&gt; sub_that_might_use_try_eval&#40;&#41;;
&gt; catch my $error;
&gt;
&gt; You should be catching errors where you eval.
&gt;   
</div>I think, I see your point, but I&#39;m not sure, that I can agree.
I assume, that the above &#34;catch my error;&#34; are &#34;if&#40;catch my $error&#41; { 
some error handling }&#34;.
At first it shouldn&#39;t matter, whether the try eval-block is in- or 
outside a subroutine. &#40;But your point is a reliable 1:1 match between 
try and catch.&#41;
Second: What happens, if the eval block exits with no error? I expect, 
that in this case &#34;catch my $error&#34; should return false or undef and the 
if-branch isn&#39;t executed &#40;and $error should be undef&#41;.
 From this point of view even the second example makes sense.
Can you follow this perspective?
<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; That&#39;s a fair point.  I suppose you could override $SIG{__DIE__} to
&gt; throw whatever exception you want, but that could break anything
&gt; *else* that uses $SIG{__DIE__}.  Perhaps I can add a way for a user to
&gt; specify an Exception::Class they want TryCatch to use for die instead
&gt; of Base.
&gt;   
</div>We are on common ground, that overriding $SIG{__DIE__} is rather 
dangerous. And I feel, that I&#39;m not expert enough to overview all 
consequences, when including this into a complex perl program.
But you&#39;re idea sounds to me as the perfect solution. The user of 
TryCatch should know, what class is the right for these non-throw 
exceptions.
<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; You&#39;ve raised two good interface ideas.  I&#39;m putting them into my
&gt; &#39;todo&#39; for TryCatch.  No promises on when I&#39;ll get a chance to
&gt; implement them, though.  Feel free to ask me again in a couple weeks
&gt; if I haven&#39;t gotten around to it.
&gt;   
</div>I&#39;m looking forward to it. Thanks.

Regards,

Oliver
</div></div>
    </div>
</div>
</div>
<div class="ticket-transaction message Correspond odd">
<div class="ticket-transaction">
  <div class="metadata">
    <span class="type">
      &nbsp;      
    </span>
    <span class="date">Tue&nbsp;Mar&nbsp;03&nbsp;17:36:49&nbsp;2009</span>
    <span class="description">dagolden [...] cpan.org -  Correspondence added</span>
    <span class="time-taken"></span>    <span class="actions hidden"></span>
  </div>
    <div class="content">
      
<table>
  <tr>
    <td align="right" class="message-header-key">Subject:</td>
    <td class="message-header-value"> Re: [rt.cpan.org #43759] Questions about TryCatch&#39;s philosophy</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">Date:</td>
    <td class="message-header-value"> Tue, 3 Mar 2009 17:36:09 -0500</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">To:</td>
    <td class="message-header-value"> bug-Exception-Class-TryCatch [...] rt.cpan.org</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">From:</td>
    <td class="message-header-value"> David Golden &lt;dagolden [...] cpan.org&gt;</td>
  </tr>
</table>

<div class="messagebody">
<div class="message-stanza plain-text-white-space">On Tue, Mar 3, 2009 at 3:13 PM, Oliver Koch via RT
&lt;bug-Exception-Class-TryCatch@rt.cpan.org&gt; wrote:
<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed"><div class="message-stanza open">&gt;&gt; It makes perfect sense to do this:
&gt;&gt;
&gt;&gt; try eval { sub_that_throws_exception&#40;&#41; };
&gt;&gt; catch my $error;
&gt;&gt;
&gt;&gt; It *doesn&#39;t* make sense to do this:
&gt;&gt;
&gt;&gt; sub_that_might_use_try_eval&#40;&#41;;
&gt;&gt; catch my $error;
&gt;&gt;
&gt;&gt; You should be catching errors where you eval.
&gt;&gt;
</div>&gt; I think, I see your point, but I&#39;m not sure, that I can agree.
&gt; I assume, that the above &#34;catch my error;&#34; are &#34;if&#40;catch my $error&#41; {
&gt; some error handling }&#34;.
</div>
Yes.

<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; At first it shouldn&#39;t matter, whether the try eval-block is in- or
&gt; outside a subroutine. &#40;But your point is a reliable 1:1 match between
&gt; try and catch.&#41;
&gt; Second: What happens, if the eval block exits with no error? I expect,
&gt; that in this case &#34;catch my $error&#34; should return false or undef and the
&gt; if-branch isn&#39;t executed &#40;and $error should be undef&#41;.
&gt;  From this point of view even the second example makes sense.
&gt; Can you follow this perspective?
</div>
Technically, I agree.  But in practice, I think you should have try&#40;&#41;
and catch&#40;&#41; in the same scope.  Why?  Because it indicates the
granularity of what you care about.

For example:

try eval {
  # stuff
  sub_that_throws_exception&#40;&#41;;
  # stuff
}
if &#40; catch my $err &#41; { ... }

This makes it clear what you want to catch.

The only reason that I could see to do it differently is if you want
to silently accumulate all exceptions *without stopping execution* and
then process/log all exceptions afterwards:

stuff_that_uses_try_eval&#40;&#41;;
while &#40;my $err = catch &#41; {    # assuming I fix catch to do this properly
  # handle each $err
}

So if I fix catch, yes, you *can* do that, but I wouldn&#39;t consider it
good style.  I think it could be hard for someone who didn&#39;t write the
code to follow it.  Compare to this:

my @error_log;

sub stuff_that_uses_try_eval {
  # stuff
  try eval {
    # dangerous stuff
  };
  catch my $err and push @error_log, $err;
  # continue
}

stuff_that_uses_try_eval&#40;&#41;;
for my $err &#40; @error_log &#41; {
  # handle each $err
}

That makes it explicit at the point you call eval{} exactly what
happens with an exception -- in this case, it&#39;s pushed to a global
error log array.  You could just as easily record the error in other
ways.

-- David
</div></div>
    </div>
</div>
</div>
<div class="ticket-transaction message Correspond even">
<div class="ticket-transaction">
  <div class="metadata">
    <span class="type">
      &nbsp;      
    </span>
    <span class="date">Wed&nbsp;Mar&nbsp;04&nbsp;17:06:46&nbsp;2009</span>
    <span class="description">QKoch [...] web.de -  Correspondence added</span>
    <span class="time-taken"></span>    <span class="actions hidden"></span>
  </div>
    <div class="content">
      
<table>
  <tr>
    <td align="right" class="message-header-key">Subject:</td>
    <td class="message-header-value"> Re: [rt.cpan.org #43759] Questions about TryCatch&#39;s philosophy</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">Date:</td>
    <td class="message-header-value"> Wed, 04 Mar 2009 22:30:37 +0100</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">To:</td>
    <td class="message-header-value"> bug-Exception-Class-TryCatch [...] rt.cpan.org</td>
  </tr>
  <tr>
    <td align="right" class="message-header-key">From:</td>
    <td class="message-header-value"> Oliver Koch &lt;QKoch [...] web.de&gt;</td>
  </tr>
</table>
<div class="messageattachments">

<div class="messagebody">
<div class="message-stanza plain-text-white-space">Dear David,

David Golden via RT schrieb:
<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; &lt;URL: <span class="clickylink"><a target="new" rel="nofollow" href="http://rt.cpan.org/Ticket/Display.html?id=43759">http://rt.cpan.org/Ticket/Display.html?id=43759</a></span> &gt;
&gt;   
<div class="message-stanza open">&gt;&gt; At first it shouldn&#39;t matter, whether the try eval-block is in- or
&gt;&gt; outside a subroutine. &#40;But your point is a reliable 1:1 match between
&gt;&gt; try and catch.&#41;
&gt;&gt; Second: What happens, if the eval block exits with no error? I expect,
&gt;&gt; that in this case &#34;catch my $error&#34; should return false or undef and the
&gt;&gt; if-branch isn&#39;t executed &#40;and $error should be undef&#41;.
&gt;&gt;  From this point of view even the second example makes sense.
&gt;&gt; Can you follow this perspective?
&gt;&gt;     
</div>&gt;
&gt; Technically, I agree.  But in practice, I think you should have try&#40;&#41;
&gt; and catch&#40;&#41; in the same scope.  Why?  Because it indicates the
&gt; granularity of what you care about.
&gt;
&gt; For example:
&gt;
&gt; try eval {
&gt;   # stuff
&gt;   sub_that_throws_exception&#40;&#41;;
&gt;   # stuff
&gt; }
&gt; if &#40; catch my $err &#41; { ... }
&gt;
&gt; This makes it clear what you want to catch.
&gt;   
</div>I agree.
<span
    class="message-stanza-folder closed"
    onclick="fold_message_stanza(this, 'Show\x20quoted\x20text', 'Hide\x20quoted\x20text');">Show quoted text</span><br /><div class="message-stanza closed">&gt; The only reason that I could see to do it differently is if you want
&gt; to silently accumulate all exceptions *without stopping execution* and
&gt; then process/log all exceptions afterwards:
&gt;
&gt; stuff_that_uses_try_eval&#40;&#41;;
&gt; while &#40;my $err = catch &#41; {    # assuming I fix catch to do this properly
&gt;   # handle each $err
&gt; }
&gt;   
</div>Indeed, this was with some respect my intention:
 From my survey in the web exception handling seems to have some 
philosophical aspect.
There are developers, who use exceptions to handle something, that is 
really exceptional &#40;like a divide by 0&#41;. This seems to be an enhancement 
compared to old programs, that just crashed in such situations.
In the other corner you find developers, who treat exception handling as 
an additional channel &#40;next to the normal return value of a function&#41; 
for passing back errors.
In between you might find any possible grade of opinion. &#40;It seems, that 
I tend to the latter fraction.&#41;

However, let&#39;s come back to the point.
I want to be sure, that I report all exceptions to the user.
And I can&#39;t always guarantee, that every exception is handled in the 
place where it happens.
My program should look like this:
sub do_b_might_throw_ex {
  do_d_might_throw_ex_but_cant_handle;
  try eval {
    do_e_might_throw_ex;
  }
  if&#40;catch my $ex&#41; {
    if&#40;$ex-&gt;isa&#40;&#34;e&#34;&#41; {
      cure_error_e;
    } else {
      $ex-&gt;rethrow;
    }
  }
  do_f;
}
try eval {
  do_a_might_throw_ex_but_cant_handle;
  try eval {
    do_b_might_throw_ex;
  }
  if&#40;catch my $ex&#41; {
    if&#40;$ex-&gt;isa&#40;&#34;b&#34;&#41; {
      cure_error_b;
    } else {
      $ex-&gt;rethrow;
    }
  }
  do_c;
}
clean_up;
while&#40;catch my $ex&#41; {
  print $ex-&gt;error;
  exit&#40;-1&#41;;
}

So, if I really think it over, I realize, that the while loop at the end 
is somehow paranoiac. An if should perfectly do it.

Nevertheless, I&#39;m still convinced of this approach &#40;after changing the 
while to an if&#41;.
The big advantage is from my point of view, that I don&#39;t have to pollute 
the code with exit&#40;&#41;s or die&#40;&#41;s, if I don&#39;t know to handle the problem.
&#40;Although it is very common to let a perl script die whenever something 
strange happens, I don&#39;t like this in complex programs.&#41;
 From my approach there&#39;s one central place, where unknown exceptions 
are handled and cleaning up is done. I think, this is good style, too.

I agree, that throwing three exceptions before handling it &#40;as shown in 
my first e-mail&#41;, isn&#39;t a good idea.

I think, we could discuss endless and both of us can find many sensible 
reasons ...
However, from my point of view, the discussion was very valuable and 
helpful.

I&#39;m happy, if you consider to implement the $@-switch, that brings more 
clarity in the usage of TryCatch.
The user-defined class&#40;es&#41; for die etc. would be nice, too, for a more 
appropriate error handling.
I&#39;m looking forward to an implementation.

Many thanks again for the helpful discussion.

Regards,

Oliver
</div></div>

<div class="messagebody">
</div>
</div>
    </div>
</div>
</div>
<div class="ticket-transaction message Correspond odd">
<div class="ticket-transaction">
  <div class="metadata">
    <span class="type">
      &nbsp;      
    </span>
    <span class="date">Wed&nbsp;Feb&nbsp;26&nbsp;19:21:51&nbsp;2014</span>
    <span class="description">dagolden [...] cpan.org -  Correspondence added</span>
    <span class="time-taken"></span>    <span class="actions hidden"></span>
  </div>
    <div class="content">
      

<div class="messagebody">
<div class="message-stanza plain-text-white-space">Marking this 5 year old ticket resolved as there&#39;s nothing to do about it.  Try::Tiny has largely superceded this module anyway.
</div></div>
    </div>
</div>
</div>
<div class="ticket-transaction basics Status even">
<div class="ticket-transaction">
  <div class="metadata">
    <span class="type">
      &nbsp;      
    </span>
    <span class="date">Wed&nbsp;Feb&nbsp;26&nbsp;19:21:52&nbsp;2014</span>
    <span class="description">dagolden [...] cpan.org -  Status changed from &#39;open&#39; to &#39;resolved&#39;</span>
    <span class="time-taken"></span>    <span class="actions hidden"></span>
  </div>
    <div class="content">
    </div>
</div>
</div>
</div>
    <hr class="clear" />
  </div>
</div>




</div>
 


  <hr class="clear" />
</div>
</body>
</html>
